# Generated by Django 2.1.3 on 2018-11-21 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField()),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OR_web_GUI.Inputs')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OR_web_GUI.Outputs')),
            ],
        ),
    ]
