# Generated by Django 2.1.3 on 2018-11-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OR_web_GUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='channel',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
