# Generated by Django 2.1.3 on 2019-02-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OR_web_GUI', '0002_output_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='last_used',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
